# See this template here: 
# https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/-/blob/master/.gitlab-ci.yml
default:
  image: julia:latest
  before_script:
  - apt-get -qq update; apt-get -y --no-install-recommends install git qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools at-spi2-core libgtk-3-dev xauth xvfb gconf-gsettings-backend
  - export GKSwstype="100"
  - git clone https://github.com/junglegobs/TimeSeriesClustering.jl.git ./TimeSeriesClustering.jl/

test:1.2:
  image: julia:1.2.0
  script:
    - julia --project=test -e 'using Pkg; Pkg.rm("HiGHS")'
    - julia --project=test -e 'import Pkg; Pkg.build()'
    - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); include("test/minimal_tests.jl")'
  only:
    - master

test:1.3:
  image: julia:1.3.1
  script:
    - julia --project=test -e 'import Pkg; Pkg.build()'
    - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); include("test/minimal_tests.jl")'
  only:
    - master

test:1.4:
  image: julia:1.4.2
  script:
    - julia --project=test -e 'import Pkg; Pkg.build()'
    - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); include("test/minimal_tests.jl")'
  only:
    - master

test:1.5:
  image: julia:1.5.4
  script:
    - julia --project=test -e 'import Pkg; Pkg.build()'
    - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); include("test/minimal_tests.jl")'
  only:
    - master

test:1.6:
  image: julia:1.6.6
  script:
    - julia --project=test -e 'import Pkg; Pkg.build()'
    - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); include("test/minimal_tests.jl")'
  only:
    - master

test:latest:
  image: julia:latest
  script:
    # - julia --project=test -e 'ENV["GKSwstype"]="nul"; ENV["PLOTS_TEST"] = "true"; ENV["GRDIR"] = ""; import Pkg; Pkg.build();' # build the test environment
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage=true)" # test the package
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()' # Setup coverage environment
    - julia --project=test/coverage test/coverage/coverage_summary.jl # run coverage summary
  coverage: '/Code coverage: \d+\.\d+/' # Regex expression to determine coverage
  only:
  - dev

pages:
  # stage: deploy # Have this done every time
  script:
    - julia --project=docs -e 'using Pkg; Pkg.develop(path=pwd()); Pkg.instantiate();' 
    # Instantiate docs environment and dev the package to add it to environment
    - julia --project=docs --color=yes docs/make.jl # build the docs
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
