# See this template here: 
# https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/-/blob/master/.gitlab-ci.yml
default:
  image: julia:latest

  before_script:
  - apt-get -qq update; apt-get -y --no-install-recommends install git qt5-default at-spi2-core libgtk-3-dev xauth xvfb gconf-gsettings-backend
  - export GKSwstype="nul"
  - julia --project=@. -e """ENV["GKSwstype"]="nul""""
  - julia --project=@. -e "import Pkg; Pkg.build()" # build the package

test:latest:
  image: julia:latest
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage=true)" # test the package
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()' # Setup coverage environment
    - julia --project=test/coverage test/coverage/coverage_summary.jl # run coverage summary
  coverage: '/Code coverage: \d+\.\d+/' # Regex expression to determine coverage
  only:
  - master
  - dev

test:1.5:
  image: julia:1.5.4
  script:
    - julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); include("test/minimal_tests.jl")'
  only:
    - master

pages:
  stage: deploy
  script:
    - julia --project=docs -e 'using Pkg; Pkg.develop(path=pwd()); Pkg.instantiate();'
    # Instantiate docs environment and dev the package to add it to environment
    - julia --project=docs --color=yes docs/make.jl # build the docs
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master
    - dev